Fixed missed unchanged atribute names.
Got this error:
File "/home/bushman/Projects/CNC_stuff/dxf2gcode/dxf2gcode-
sourcecode/source/Core/BreakGeo.py", line 87, in Write_GCode
    self.inner.Write_GCode(parent, PostPro)
AttributeError: 'BreakGeo' object has no attribute 'inner'

Don't know why it was changed but it was not changed in all places in
the file. Changed missing instances to new name.