Fix for #83, AttributeError: 'NoneType' object has no attribute 'select'
Traceback (most recent call last):
  File "source/gui/treeview.py", line 280, in selectionChanged
    self.selectionChangedcallback(self, selected, deselected)
  File "source/gui/treehandling.py", line 1104, in actionOnSelectionChange
    selectionLayer.select(itemLayerSelection, QItemSelectionModel.Deselect | QItemSelectionModel.Rows)
AttributeError: 'NoneType' object has no attribute 'select'

This happens because the self.ui.layersShapesTreeView.selectionModel() function returns None
however the call is triggered by the following function:

  treeview.py:280   self.ui.entitiesTreeView.setModel(self.entity_item_model)

which explains why the selectionModel() is still not available yet.

This fix simply returns from the function if selectionModel() is None.

Fix seems to work fine on both Fedora Linux and Windows 7.