Reverting commit 361065354fcb97ae60f755f888d2f376c64001a6 (Fix for automatic cutter compensation toggle off), because it is wrong (No automatic compensation doesn't mean no compensation at all, it just means that the cutter compensation is not automatic). See https://groups.google.com/forum/#!topic/dxf2gcode-dev/vq4ntIyZWyM for more details. This commit also fix the bug "AttributeError: 'CustomGCode' object has no attribute 'cut_cor'" that was triggered when loading a .d2g project file containing special shapes (CustomGCode).