Revert "* Fixed a old nasty bug that would cause broken G-code export after invoking Shape.setNearestStPoint()"
This reverts commit de18ef31e2338e8df5c0d00e225b7c859407bfd5.

Reverted as it broke 69 tests!

Broken test reported (depending on the platform):
  - Linux: Error exporting shapes: list index out of range
or
  - Windows: AttributeError: 'StMoveGUI' object has no attribute 'geos'